version: 2.1

executors:
  e2e-tests-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.50.1-noble
    resource_class: small

jobs:
  e2e-tests:
    executor: e2e-tests-executor
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps
      - run:
          name: Run Playwright Tests
          command: npm run test -- --shard=${CIRCLE_NODE_INDEX+1}/${CIRCLE_NODE_TOTAL}
      - store_test_results:
          path: test-results  # Store JUnit XML reports
      - store_artifacts:
         path: playwright-report  # Store HTML report for debugging


workflows:
  version: 2.1
  e2e-tests:
    jobs:
      - e2e-tests
#  scheduled-workflow:
#    triggers:
#      - schedule:
#          cron: "30 10 * * *"
#          filters:
#            branches:
#              only: main
#    jobs:
#      - e2e-tests

