version: 2.1

jobs:
  test:
    docker:
      # Use a Node.js Docker image with Playwright dependencies pre-installed
      - image: mcr.microsoft.com/playwright:v1.39.0-focal
    steps:
      # Step 1: Check out the code from the repository
      - checkout

      # Step 2: Install Node.js dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Step 3: Install Playwright browsers
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps

      # Step 4: Run Playwright tests
      - run:
          name: Run Playwright Tests
          command: npx playwright test

workflows:
  version: 2
  test:
    jobs:
      - test