version: 2.1

jobs:
test:
docker:
      # Use a Node.js Docker image with Playwright dependencies pre-installed
      - image: mcr.microsoft.com/playwright:v1.39.0-focal
working_directory: ~/project/playwright/playwright  # Navigate to the subdirectory with package.json
steps:
  - checkout
  - - run:
        name: Debug Working Directory
        command: ls -la
  - run:
      name: Install Dependencies
      command: |
        cd playwright
        npm install
  - run:
      name: Install Playwright Browsers
      command: |
        cd playwright
        npx playwright install --with-deps
  - run:
      name: Run Playwright Tests
      command: |
        cd playwright
        npm run test

workflows:
  version: 2
  test:
    jobs:
      - test