version: 2.1

jobs:
  e2e tests:
    docker:
      # Use a Node.js Docker image with Playwright dependencies pre-installed
      - image: mcr.microsoft.com/playwright:v1.39.0-focal
    steps:
      # Step 1: Check out the code from the repository
      - checkout

      # Step 2: Install Node.js dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Step 3: Install Playwright browsers
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps

      # Step 4: Run Playwright tests
      - run:
          name: Run Playwright Tests
          command: npm run test
      - store_test_results:
          path: test-results  # Store JUnit XML reports

      - store_artifacts:
         path: playwright-report  # Store HTML report for debugging

workflows:
  version: 2
  test:
    jobs:
      - e2e tests